hpc<-read.table('household_power_consumption.txt',header=TRUE,na.strings='?',stringsAsFactors=FALSE,sep=';')
hpc$Date<-as.Date(hpc$Date,'%d/%m/%Y')
hpc$Time<-strptime(paste(hpc$Date,hpc$Time),"%Y-%m-%d %H:%M:%S")
png('plot4.png')
par(mfrow=c(2,2))
with(subset(hpc,Date %in% c(as.Date('2007-02-01'),as.Date('2007-02-02'))),plot(Time,Global_active_power,type='l',xlab = "",ylab = 'Global active power (kilowatts)'))
with(subset(hpc,Date %in% c(as.Date('2007-02-01'),as.Date('2007-02-02'))),plot(Time,Voltage,type='l',xlab='datetime'))
with(subset(hpc,Date %in% c(as.Date('2007-02-01'),as.Date('2007-02-02'))),plot(Time,Sub_metering_1,type='l',col='black',xlab="",ylab='Energy sub metering'))
with(subset(hpc,Date %in% c(as.Date('2007-02-01'),as.Date('2007-02-02'))),lines(Time,Sub_metering_2,col='red'))
with(subset(hpc,Date %in% c(as.Date('2007-02-01'),as.Date('2007-02-02'))),lines(Time,Sub_metering_3,col='blue'))
legend("topright",legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),col=c('black','red','blue'),lty=1)
with(subset(hpc,Date %in% c(as.Date('2007-02-01'),as.Date('2007-02-02'))),plot(Time,Global_reactive_power,type='l',xlab='datetime'))
dev.off()