hpc<-read.table('household_power_consumption.txt',header=TRUE,na.strings='?',stringsAsFactors=FALSE,sep=';')
hpc$Date<-as.Date(hpc$Date,'%d/%m/%Y')
hpc$Time<-strptime(paste(hpc$Date,hpc$Time),"%Y-%m-%d %H:%M:%S")
png('plot3.png')
with(subset(hpc,Date %in% c(as.Date('2007-02-01'),as.Date('2007-02-02'))),plot(Time,Sub_metering_1,type='l',col='black',main=NA,xlab="",ylab='Energy sub metering'))
with(subset(hpc,Date %in% c(as.Date('2007-02-01'),as.Date('2007-02-02'))),lines(Time,Sub_metering_2,col='red'))
with(subset(hpc,Date %in% c(as.Date('2007-02-01'),as.Date('2007-02-02'))),lines(Time,Sub_metering_3,col='blue'))
legend("topright",legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),col=c('black','red','blue'),lty=1)
dev.off()